### POST request to create patient
POST http://localhost:4002/patients
Content-Type:application/json

{
  "name": "Raghav",
  "email": "katyal897@gmail.com",
  "address": "Blr",
  "dateOfBirth": "2004-01-15",
  "registeredDate": "2026-04-05"
}

